# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoactor/remote/protos_remote.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoactor.actor import protos_pb2 as protoactor_dot_actor_dot_protos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoactor/remote/protos_remote.proto',
  package='remote',
  syntax='proto3',
  serialized_options=_b('\252\002\014Proto.remote'),
  serialized_pb=_b('\n%protoactor/remote/protos_remote.proto\x12\x06remote\x1a\x1dprotoactor/actor/protos.proto\"d\n\x0cMessageBatch\x12\x12\n\ntype_names\x18\x01 \x03(\t\x12\x14\n\x0ctarget_names\x18\x02 \x03(\t\x12*\n\tenvelopes\x18\x03 \x03(\x0b\x32\x17.remote.MessageEnvelope\"\xaa\x01\n\x0fMessageEnvelope\x12\x0f\n\x07type_id\x18\x01 \x01(\x05\x12\x14\n\x0cmessage_data\x18\x02 \x01(\x0c\x12\x0e\n\x06target\x18\x03 \x01(\x05\x12\x1a\n\x06sender\x18\x04 \x01(\x0b\x32\n.actor.PID\x12\x15\n\rserializer_id\x18\x05 \x01(\x05\x12-\n\x0emessage_header\x18\x06 \x01(\x0b\x32\x15.remote.MessageHeader\"~\n\rMessageHeader\x12:\n\x0bheader_data\x18\x01 \x03(\x0b\x32%.remote.MessageHeader.HeaderDataEntry\x1a\x31\n\x0fHeaderDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"-\n\x0f\x41\x63torPidRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\"@\n\x10\x41\x63torPidResponse\x12\x17\n\x03pid\x18\x01 \x01(\x0b\x32\n.actor.PID\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"\x06\n\x04Unit\"\x10\n\x0e\x43onnectRequest\"0\n\x0f\x43onnectResponse\x12\x1d\n\x15\x64\x65\x66\x61ult_serializer_id\x18\x01 \x01(\x05\x32}\n\x08Remoting\x12<\n\x07\x43onnect\x12\x16.remote.ConnectRequest\x1a\x17.remote.ConnectResponse\"\x00\x12\x33\n\x07Receive\x12\x14.remote.MessageBatch\x1a\x0c.remote.Unit\"\x00(\x01\x30\x01\x42\x0f\xaa\x02\x0cProto.remoteb\x06proto3')
  ,
  dependencies=[protoactor_dot_actor_dot_protos__pb2.DESCRIPTOR,])




_MESSAGEBATCH = _descriptor.Descriptor(
  name='MessageBatch',
  full_name='remote.MessageBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_names', full_name='remote.MessageBatch.type_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_names', full_name='remote.MessageBatch.target_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='envelopes', full_name='remote.MessageBatch.envelopes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=180,
)


_MESSAGEENVELOPE = _descriptor.Descriptor(
  name='MessageEnvelope',
  full_name='remote.MessageEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_id', full_name='remote.MessageEnvelope.type_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_data', full_name='remote.MessageEnvelope.message_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='remote.MessageEnvelope.target', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='remote.MessageEnvelope.sender', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serializer_id', full_name='remote.MessageEnvelope.serializer_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_header', full_name='remote.MessageEnvelope.message_header', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=353,
)


_MESSAGEHEADER_HEADERDATAENTRY = _descriptor.Descriptor(
  name='HeaderDataEntry',
  full_name='remote.MessageHeader.HeaderDataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='remote.MessageHeader.HeaderDataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='remote.MessageHeader.HeaderDataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=481,
)

_MESSAGEHEADER = _descriptor.Descriptor(
  name='MessageHeader',
  full_name='remote.MessageHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header_data', full_name='remote.MessageHeader.header_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGEHEADER_HEADERDATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=481,
)


_ACTORPIDREQUEST = _descriptor.Descriptor(
  name='ActorPidRequest',
  full_name='remote.ActorPidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='remote.ActorPidRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='remote.ActorPidRequest.kind', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=528,
)


_ACTORPIDRESPONSE = _descriptor.Descriptor(
  name='ActorPidResponse',
  full_name='remote.ActorPidResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='remote.ActorPidResponse.pid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='remote.ActorPidResponse.status_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=594,
)


_UNIT = _descriptor.Descriptor(
  name='Unit',
  full_name='remote.Unit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=596,
  serialized_end=602,
)


_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='remote.ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=604,
  serialized_end=620,
)


_CONNECTRESPONSE = _descriptor.Descriptor(
  name='ConnectResponse',
  full_name='remote.ConnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='default_serializer_id', full_name='remote.ConnectResponse.default_serializer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=670,
)

_MESSAGEBATCH.fields_by_name['envelopes'].message_type = _MESSAGEENVELOPE
_MESSAGEENVELOPE.fields_by_name['sender'].message_type = protoactor_dot_actor_dot_protos__pb2._PID
_MESSAGEENVELOPE.fields_by_name['message_header'].message_type = _MESSAGEHEADER
_MESSAGEHEADER_HEADERDATAENTRY.containing_type = _MESSAGEHEADER
_MESSAGEHEADER.fields_by_name['header_data'].message_type = _MESSAGEHEADER_HEADERDATAENTRY
_ACTORPIDRESPONSE.fields_by_name['pid'].message_type = protoactor_dot_actor_dot_protos__pb2._PID
DESCRIPTOR.message_types_by_name['MessageBatch'] = _MESSAGEBATCH
DESCRIPTOR.message_types_by_name['MessageEnvelope'] = _MESSAGEENVELOPE
DESCRIPTOR.message_types_by_name['MessageHeader'] = _MESSAGEHEADER
DESCRIPTOR.message_types_by_name['ActorPidRequest'] = _ACTORPIDREQUEST
DESCRIPTOR.message_types_by_name['ActorPidResponse'] = _ACTORPIDRESPONSE
DESCRIPTOR.message_types_by_name['Unit'] = _UNIT
DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectResponse'] = _CONNECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageBatch = _reflection.GeneratedProtocolMessageType('MessageBatch', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEBATCH,
  '__module__' : 'protoactor.remote.protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.MessageBatch)
  })
_sym_db.RegisterMessage(MessageBatch)

MessageEnvelope = _reflection.GeneratedProtocolMessageType('MessageEnvelope', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEENVELOPE,
  '__module__' : 'protoactor.remote.protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.MessageEnvelope)
  })
_sym_db.RegisterMessage(MessageEnvelope)

MessageHeader = _reflection.GeneratedProtocolMessageType('MessageHeader', (_message.Message,), {

  'HeaderDataEntry' : _reflection.GeneratedProtocolMessageType('HeaderDataEntry', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGEHEADER_HEADERDATAENTRY,
    '__module__' : 'protoactor.remote.protos_remote_pb2'
    # @@protoc_insertion_point(class_scope:remote.MessageHeader.HeaderDataEntry)
    })
  ,
  'DESCRIPTOR' : _MESSAGEHEADER,
  '__module__' : 'protoactor.remote.protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.MessageHeader)
  })
_sym_db.RegisterMessage(MessageHeader)
_sym_db.RegisterMessage(MessageHeader.HeaderDataEntry)

ActorPidRequest = _reflection.GeneratedProtocolMessageType('ActorPidRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTORPIDREQUEST,
  '__module__' : 'protoactor.remote.protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.ActorPidRequest)
  })
_sym_db.RegisterMessage(ActorPidRequest)

ActorPidResponse = _reflection.GeneratedProtocolMessageType('ActorPidResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTORPIDRESPONSE,
  '__module__' : 'protoactor.remote.protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.ActorPidResponse)
  })
_sym_db.RegisterMessage(ActorPidResponse)

Unit = _reflection.GeneratedProtocolMessageType('Unit', (_message.Message,), {
  'DESCRIPTOR' : _UNIT,
  '__module__' : 'protoactor.remote.protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.Unit)
  })
_sym_db.RegisterMessage(Unit)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'protoactor.remote.protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

ConnectResponse = _reflection.GeneratedProtocolMessageType('ConnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTRESPONSE,
  '__module__' : 'protoactor.remote.protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.ConnectResponse)
  })
_sym_db.RegisterMessage(ConnectResponse)


DESCRIPTOR._options = None
_MESSAGEHEADER_HEADERDATAENTRY._options = None

_REMOTING = _descriptor.ServiceDescriptor(
  name='Remoting',
  full_name='remote.Remoting',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=672,
  serialized_end=797,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='remote.Remoting.Connect',
    index=0,
    containing_service=None,
    input_type=_CONNECTREQUEST,
    output_type=_CONNECTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Receive',
    full_name='remote.Remoting.Receive',
    index=1,
    containing_service=None,
    input_type=_MESSAGEBATCH,
    output_type=_UNIT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTING)

DESCRIPTOR.services_by_name['Remoting'] = _REMOTING

# @@protoc_insertion_point(module_scope)
