# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples/chat/messages/chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoactor.actor import protos_pb2 as protoactor_dot_actor_dot_protos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='examples/chat/messages/chat.proto',
  package='messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!examples/chat/messages/chat.proto\x12\x08messages\x1a\x1dprotoactor/actor/protos.proto\"%\n\x07\x43onnect\x12\x1a\n\x06sender\x18\x01 \x01(\x0b\x32\n.actor.PID\"\x1c\n\tConnected\x12\x0f\n\x07message\x18\x01 \x01(\t\"0\n\nSayRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\x0bSayResponse\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\x0bNickRequest\x12\x15\n\rold_user_name\x18\x01 \x01(\t\x12\x15\n\rnew_user_name\x18\x02 \x01(\t\"<\n\x0cNickResponse\x12\x15\n\rold_user_name\x18\x01 \x01(\t\x12\x15\n\rnew_user_name\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[protoactor_dot_actor_dot_protos__pb2.DESCRIPTOR,])




_CONNECT = _descriptor.Descriptor(
  name='Connect',
  full_name='messages.Connect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='messages.Connect.sender', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=115,
)


_CONNECTED = _descriptor.Descriptor(
  name='Connected',
  full_name='messages.Connected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='messages.Connected.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=145,
)


_SAYREQUEST = _descriptor.Descriptor(
  name='SayRequest',
  full_name='messages.SayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='messages.SayRequest.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='messages.SayRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=195,
)


_SAYRESPONSE = _descriptor.Descriptor(
  name='SayResponse',
  full_name='messages.SayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='messages.SayResponse.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='messages.SayResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=246,
)


_NICKREQUEST = _descriptor.Descriptor(
  name='NickRequest',
  full_name='messages.NickRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='old_user_name', full_name='messages.NickRequest.old_user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_user_name', full_name='messages.NickRequest.new_user_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=307,
)


_NICKRESPONSE = _descriptor.Descriptor(
  name='NickResponse',
  full_name='messages.NickResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='old_user_name', full_name='messages.NickResponse.old_user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_user_name', full_name='messages.NickResponse.new_user_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=369,
)

_CONNECT.fields_by_name['sender'].message_type = protoactor_dot_actor_dot_protos__pb2._PID
DESCRIPTOR.message_types_by_name['Connect'] = _CONNECT
DESCRIPTOR.message_types_by_name['Connected'] = _CONNECTED
DESCRIPTOR.message_types_by_name['SayRequest'] = _SAYREQUEST
DESCRIPTOR.message_types_by_name['SayResponse'] = _SAYRESPONSE
DESCRIPTOR.message_types_by_name['NickRequest'] = _NICKREQUEST
DESCRIPTOR.message_types_by_name['NickResponse'] = _NICKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Connect = _reflection.GeneratedProtocolMessageType('Connect', (_message.Message,), {
  'DESCRIPTOR' : _CONNECT,
  '__module__' : 'examples.chat.messages.chat_pb2'
  # @@protoc_insertion_point(class_scope:messages.Connect)
  })
_sym_db.RegisterMessage(Connect)

Connected = _reflection.GeneratedProtocolMessageType('Connected', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTED,
  '__module__' : 'examples.chat.messages.chat_pb2'
  # @@protoc_insertion_point(class_scope:messages.Connected)
  })
_sym_db.RegisterMessage(Connected)

SayRequest = _reflection.GeneratedProtocolMessageType('SayRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAYREQUEST,
  '__module__' : 'examples.chat.messages.chat_pb2'
  # @@protoc_insertion_point(class_scope:messages.SayRequest)
  })
_sym_db.RegisterMessage(SayRequest)

SayResponse = _reflection.GeneratedProtocolMessageType('SayResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAYRESPONSE,
  '__module__' : 'examples.chat.messages.chat_pb2'
  # @@protoc_insertion_point(class_scope:messages.SayResponse)
  })
_sym_db.RegisterMessage(SayResponse)

NickRequest = _reflection.GeneratedProtocolMessageType('NickRequest', (_message.Message,), {
  'DESCRIPTOR' : _NICKREQUEST,
  '__module__' : 'examples.chat.messages.chat_pb2'
  # @@protoc_insertion_point(class_scope:messages.NickRequest)
  })
_sym_db.RegisterMessage(NickRequest)

NickResponse = _reflection.GeneratedProtocolMessageType('NickResponse', (_message.Message,), {
  'DESCRIPTOR' : _NICKRESPONSE,
  '__module__' : 'examples.chat.messages.chat_pb2'
  # @@protoc_insertion_point(class_scope:messages.NickResponse)
  })
_sym_db.RegisterMessage(NickResponse)


# @@protoc_insertion_point(module_scope)
