# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos_remote.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos_pb2 as protos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos_remote.proto',
  package='remote',
  syntax='proto3',
  serialized_pb=_b('\n\x13protos_remote.proto\x12\x06remote\x1a\x0cprotos.proto\"d\n\x0cMessageBatch\x12\x12\n\ntype_names\x18\x01 \x03(\t\x12\x14\n\x0ctarget_names\x18\x02 \x03(\t\x12*\n\tenvelopes\x18\x03 \x03(\x0b\x32\x17.remote.MessageEnvelope\"d\n\x0fMessageEnvelope\x12\x0f\n\x07type_id\x18\x01 \x01(\x05\x12\x14\n\x0cmessage_data\x18\x02 \x01(\x0c\x12\x0e\n\x06target\x18\x03 \x01(\x05\x12\x1a\n\x06sender\x18\x04 \x01(\x0b\x32\n.actor.PID\"-\n\x0f\x41\x63torPidRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\"+\n\x10\x41\x63torPidResponse\x12\x17\n\x03pid\x18\x01 \x01(\x0b\x32\n.actor.PID\"\x06\n\x04Unit2?\n\x08Remoting\x12\x33\n\x07Receive\x12\x14.remote.MessageBatch\x1a\x0c.remote.Unit\"\x00(\x01\x30\x01\x42\x0f\xaa\x02\x0cProto.Remoteb\x06proto3')
  ,
  dependencies=[protos__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESSAGEBATCH = _descriptor.Descriptor(
  name='MessageBatch',
  full_name='remote.MessageBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_names', full_name='remote.MessageBatch.type_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_names', full_name='remote.MessageBatch.target_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='envelopes', full_name='remote.MessageBatch.envelopes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=145,
)


_MESSAGEENVELOPE = _descriptor.Descriptor(
  name='MessageEnvelope',
  full_name='remote.MessageEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_id', full_name='remote.MessageEnvelope.type_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_data', full_name='remote.MessageEnvelope.message_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='remote.MessageEnvelope.target', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender', full_name='remote.MessageEnvelope.sender', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=247,
)


_ACTORPIDREQUEST = _descriptor.Descriptor(
  name='ActorPidRequest',
  full_name='remote.ActorPidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='remote.ActorPidRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kind', full_name='remote.ActorPidRequest.kind', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=294,
)


_ACTORPIDRESPONSE = _descriptor.Descriptor(
  name='ActorPidResponse',
  full_name='remote.ActorPidResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='remote.ActorPidResponse.pid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=339,
)


_UNIT = _descriptor.Descriptor(
  name='Unit',
  full_name='remote.Unit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=347,
)

_MESSAGEBATCH.fields_by_name['envelopes'].message_type = _MESSAGEENVELOPE
_MESSAGEENVELOPE.fields_by_name['sender'].message_type = protos__pb2._PID
_ACTORPIDRESPONSE.fields_by_name['pid'].message_type = protos__pb2._PID
DESCRIPTOR.message_types_by_name['MessageBatch'] = _MESSAGEBATCH
DESCRIPTOR.message_types_by_name['MessageEnvelope'] = _MESSAGEENVELOPE
DESCRIPTOR.message_types_by_name['ActorPidRequest'] = _ACTORPIDREQUEST
DESCRIPTOR.message_types_by_name['ActorPidResponse'] = _ACTORPIDRESPONSE
DESCRIPTOR.message_types_by_name['Unit'] = _UNIT

MessageBatch = _reflection.GeneratedProtocolMessageType('MessageBatch', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEBATCH,
  __module__ = 'protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.MessageBatch)
  ))
_sym_db.RegisterMessage(MessageBatch)

MessageEnvelope = _reflection.GeneratedProtocolMessageType('MessageEnvelope', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEENVELOPE,
  __module__ = 'protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.MessageEnvelope)
  ))
_sym_db.RegisterMessage(MessageEnvelope)

ActorPidRequest = _reflection.GeneratedProtocolMessageType('ActorPidRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACTORPIDREQUEST,
  __module__ = 'protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.ActorPidRequest)
  ))
_sym_db.RegisterMessage(ActorPidRequest)

ActorPidResponse = _reflection.GeneratedProtocolMessageType('ActorPidResponse', (_message.Message,), dict(
  DESCRIPTOR = _ACTORPIDRESPONSE,
  __module__ = 'protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.ActorPidResponse)
  ))
_sym_db.RegisterMessage(ActorPidResponse)

Unit = _reflection.GeneratedProtocolMessageType('Unit', (_message.Message,), dict(
  DESCRIPTOR = _UNIT,
  __module__ = 'protos_remote_pb2'
  # @@protoc_insertion_point(class_scope:remote.Unit)
  ))
_sym_db.RegisterMessage(Unit)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\014Proto.Remote'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class RemotingStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Receive = channel.stream_stream(
          '/remote.Remoting/Receive',
          request_serializer=MessageBatch.SerializeToString,
          response_deserializer=Unit.FromString,
          )


  class RemotingServicer(object):

    def Receive(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_RemotingServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Receive': grpc.stream_stream_rpc_method_handler(
            servicer.Receive,
            request_deserializer=MessageBatch.FromString,
            response_serializer=Unit.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'remote.Remoting', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaRemotingServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Receive(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaRemotingStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Receive(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()


  def beta_create_Remoting_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('remote.Remoting', 'Receive'): MessageBatch.FromString,
    }
    response_serializers = {
      ('remote.Remoting', 'Receive'): Unit.SerializeToString,
    }
    method_implementations = {
      ('remote.Remoting', 'Receive'): face_utilities.stream_stream_inline(servicer.Receive),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Remoting_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('remote.Remoting', 'Receive'): MessageBatch.SerializeToString,
    }
    response_deserializers = {
      ('remote.Remoting', 'Receive'): Unit.FromString,
    }
    cardinalities = {
      'Receive': cardinality.Cardinality.STREAM_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'remote.Remoting', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
