# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoactor/сluster/protos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoactor.actor import protos_pb2 as protoactor_dot_actor_dot_protos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoactor/сluster/protos.proto',
  package='cluster',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n protoactor/\xd1\x81luster/protos.proto\x12\x07\x63luster\x1a\x1dprotoactor/actor/protos.proto\"6\n\rTakeOwnership\x12\x17\n\x03pid\x18\x01 \x01(\x0b\x32\n.actor.PID\x12\x0c\n\x04name\x18\x02 \x01(\t\":\n\x0cGrainRequest\x12\x14\n\x0cmethod_index\x18\x01 \x01(\x05\x12\x14\n\x0cmessage_data\x18\x02 \x01(\x0c\"%\n\rGrainResponse\x12\x14\n\x0cmessage_data\x18\x01 \x01(\x0c\"!\n\x12GrainErrorResponse\x12\x0b\n\x03\x65rr\x18\x01 \x01(\tb\x06proto3')
  ,
  dependencies=[protoactor_dot_actor_dot_protos__pb2.DESCRIPTOR,])




_TAKEOWNERSHIP = _descriptor.Descriptor(
  name='TakeOwnership',
  full_name='cluster.TakeOwnership',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='cluster.TakeOwnership.pid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='cluster.TakeOwnership.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=130,
)


_GRAINREQUEST = _descriptor.Descriptor(
  name='GrainRequest',
  full_name='cluster.GrainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method_index', full_name='cluster.GrainRequest.method_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_data', full_name='cluster.GrainRequest.message_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=190,
)


_GRAINRESPONSE = _descriptor.Descriptor(
  name='GrainResponse',
  full_name='cluster.GrainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_data', full_name='cluster.GrainResponse.message_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=229,
)


_GRAINERRORRESPONSE = _descriptor.Descriptor(
  name='GrainErrorResponse',
  full_name='cluster.GrainErrorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='cluster.GrainErrorResponse.err', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=264,
)

_TAKEOWNERSHIP.fields_by_name['pid'].message_type = protoactor_dot_actor_dot_protos__pb2._PID
DESCRIPTOR.message_types_by_name['TakeOwnership'] = _TAKEOWNERSHIP
DESCRIPTOR.message_types_by_name['GrainRequest'] = _GRAINREQUEST
DESCRIPTOR.message_types_by_name['GrainResponse'] = _GRAINRESPONSE
DESCRIPTOR.message_types_by_name['GrainErrorResponse'] = _GRAINERRORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TakeOwnership = _reflection.GeneratedProtocolMessageType('TakeOwnership', (_message.Message,), {
  'DESCRIPTOR' : _TAKEOWNERSHIP,
  '__module__' : 'protoactor.сluster.protos_pb2'
  # @@protoc_insertion_point(class_scope:cluster.TakeOwnership)
  })
_sym_db.RegisterMessage(TakeOwnership)

GrainRequest = _reflection.GeneratedProtocolMessageType('GrainRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRAINREQUEST,
  '__module__' : 'protoactor.сluster.protos_pb2'
  # @@protoc_insertion_point(class_scope:cluster.GrainRequest)
  })
_sym_db.RegisterMessage(GrainRequest)

GrainResponse = _reflection.GeneratedProtocolMessageType('GrainResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRAINRESPONSE,
  '__module__' : 'protoactor.сluster.protos_pb2'
  # @@protoc_insertion_point(class_scope:cluster.GrainResponse)
  })
_sym_db.RegisterMessage(GrainResponse)

GrainErrorResponse = _reflection.GeneratedProtocolMessageType('GrainErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRAINERRORRESPONSE,
  '__module__' : 'protoactor.сluster.protos_pb2'
  # @@protoc_insertion_point(class_scope:cluster.GrainErrorResponse)
  })
_sym_db.RegisterMessage(GrainErrorResponse)


# @@protoc_insertion_point(module_scope)
