# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples/persistence/messages/protos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='examples/persistence/messages/protos.proto',
  package='messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n*examples/persistence/messages/protos.proto\x12\x08messages\"\x1d\n\rRenameCommand\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x0bRenameEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x15\n\x05State\x12\x0c\n\x04Name\x18\x01 \x01(\tb\x06proto3')
)




_RENAMECOMMAND = _descriptor.Descriptor(
  name='RenameCommand',
  full_name='messages.RenameCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='messages.RenameCommand.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=85,
)


_RENAMEEVENT = _descriptor.Descriptor(
  name='RenameEvent',
  full_name='messages.RenameEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='messages.RenameEvent.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=114,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='messages.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='messages.State.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['RenameCommand'] = _RENAMECOMMAND
DESCRIPTOR.message_types_by_name['RenameEvent'] = _RENAMEEVENT
DESCRIPTOR.message_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RenameCommand = _reflection.GeneratedProtocolMessageType('RenameCommand', (_message.Message,), {
  'DESCRIPTOR' : _RENAMECOMMAND,
  '__module__' : 'examples.persistence.messages.protos_pb2'
  # @@protoc_insertion_point(class_scope:messages.RenameCommand)
  })
_sym_db.RegisterMessage(RenameCommand)

RenameEvent = _reflection.GeneratedProtocolMessageType('RenameEvent', (_message.Message,), {
  'DESCRIPTOR' : _RENAMEEVENT,
  '__module__' : 'examples.persistence.messages.protos_pb2'
  # @@protoc_insertion_point(class_scope:messages.RenameEvent)
  })
_sym_db.RegisterMessage(RenameEvent)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'examples.persistence.messages.protos_pb2'
  # @@protoc_insertion_point(class_scope:messages.State)
  })
_sym_db.RegisterMessage(State)


# @@protoc_insertion_point(module_scope)
