# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoactor/cluster/providers/single_remote_instance/protos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoactor/cluster/providers/single_remote_instance/protos.proto',
  package='singleremoteinstance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nAprotoactor/\xd1\x81luster/providers/single_remote_instance/protos.proto\x12\x14singleremoteinstance\"\n\n\x08GetKinds\"!\n\x10GetKindsResponse\x12\r\n\x05kinds\x18\x01 \x03(\tb\x06proto3')
)




_GETKINDS = _descriptor.Descriptor(
  name='GetKinds',
  full_name='singleremoteinstance.GetKinds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=101,
)


_GETKINDSRESPONSE = _descriptor.Descriptor(
  name='GetKindsResponse',
  full_name='singleremoteinstance.GetKindsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kinds', full_name='singleremoteinstance.GetKindsResponse.kinds', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['GetKinds'] = _GETKINDS
DESCRIPTOR.message_types_by_name['GetKindsResponse'] = _GETKINDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetKinds = _reflection.GeneratedProtocolMessageType('GetKinds', (_message.Message,), {
  'DESCRIPTOR' : _GETKINDS,
  '__module__' : 'protoactor.cluster.providers.single_remote_instance.protos_pb2'
  # @@protoc_insertion_point(class_scope:singleremoteinstance.GetKinds)
  })
_sym_db.RegisterMessage(GetKinds)

GetKindsResponse = _reflection.GeneratedProtocolMessageType('GetKindsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETKINDSRESPONSE,
  '__module__' : 'protoactor.cluster.providers.single_remote_instance.protos_pb2'
  # @@protoc_insertion_point(class_scope:singleremoteinstance.GetKindsResponse)
  })
_sym_db.RegisterMessage(GetKindsResponse)


# @@protoc_insertion_point(module_scope)
